---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: f11

enabled: true

stickinessProperty: rox.distinct_id

defaultValue: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: tg4
    flagValue: false
  - allOf:
      - property:
          name: cp1
          operator: ne
          operands:
            - 5
    flagValue: false
