---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: newFlag12

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - anyOf:
          - group:
              name: Beta users
    flagValue: str1
