---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: poff999

enabled: true

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.language
          operator: in-array
          operands:
            - "1"
            - "2"
            - "3"
    flagValue: false
