---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag-configuration

flag: zero9

enabled: false

stickinessProperty: rox.distinct_id

defaultValue:
  valueWrittenInCode: true

conditions:
  - allOf:
      - property:
          name: rox.platform
          operator: is-undefined
    flagValue:
      valueWrittenInCode: true
