---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: flag/22
flagType: boolean
description: |-
    qqqq zxcvasdf
    qwer
    zxcv
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
