---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: num912
flagType: number
description: popopopo
labels:

availableValues:
  - "3.12"
  - "234567890"
  - "1122222333344455"

isPermanent: false
